export const MOCK_POLOS = [
  { codigo: 'RJ', rotulo: 'RJ - Rio de Janeiro', ufs: ['RJ'] },
  { codigo: 'SP', rotulo: 'SP - São Paulo', ufs: ['SP'] },
  { codigo: 'DF_PA_MS', rotulo: 'DF - PA - MS', ufs: ['DF', 'PA', 'MS'] },
  { codigo: 'MG_AM', rotulo: 'MG - AM', ufs: ['MG', 'AM'] },
  { codigo: 'BA', rotulo: 'BA - Bahia', ufs: ['BA'] },
  { codigo: 'GO_RS_MT', rotulo: 'GO - RS - MT', ufs: ['GO', 'RS', 'MT'] },
  { codigo: 'PR_RR', rotulo: 'PR - RR', ufs: ['PR', 'RR'] },
  { codigo: 'AC_AL_AP_PI_RO_SC_SE_TO', rotulo: 'AC - AL - AP - PI - RO - SC - SE - TO', ufs: ['AC', 'AL', 'AP', 'PI', 'RO', 'SC', 'SE', 'TO'] },
  { codigo: 'MA_ES_PE', rotulo: 'MA - ES - PE', ufs: ['MA', 'ES', 'PE'] },
  { codigo: 'RN_PB_CE', rotulo: 'RN - PB - CE', ufs: ['RN', 'PB', 'CE'] },
];

export const MOCK_REGRAS = [
  { id: 1, polo: 'RJ', colaboradorNome: 'Nathalia Leão', advogado: 'Dra Graziela', digitosCpf: [0], ehEscalao48h: false, departamento: 'Andamento Processual' },
  { id: 2, polo: 'RJ', colaboradorNome: 'Francielle Furtado', advogado: 'Dr Lucas Puzanovsky', digitosCpf: [1], ehEscalao48h: false, departamento: 'Andamento Processual' },
  { id: 3, polo: 'RJ', colaboradorNome: 'Marcio Freiman', advogado: 'Dr Bruno Pimentel', digitosCpf: [2], ehEscalao48h: false, departamento: 'Andamento Processual' },
  { id: 4, polo: 'SP', colaboradorNome: 'Kaio Luna', advogado: 'Dra Gabriela Torres', digitosCpf: [3, 4], ehEscalao48h: false, departamento: 'Andamento Processual' },
  { id: 5, polo: 'BA', colaboradorNome: 'João Carmo', advogado: 'Dra Debora Correa', digitosCpf: [5, 6], ehEscalao48h: false, departamento: 'Andamento Processual' },
  { id: 6, polo: 'MG_AM', colaboradorNome: 'Otavio Souza', advogado: 'Dr Diego Monteiro', digitosCpf: [7], ehEscalao48h: false, departamento: 'Andamento Processual' },
  { id: 7, polo: 'DF_PA_MS', colaboradorNome: 'Camilla Suelen', advogado: 'Dra Jéssica', digitosCpf: [8, 9], ehEscalao48h: false, departamento: 'Andamento Processual' },
  { id: 8, polo: 'GO_RS_MT', colaboradorNome: 'Raphaela Pereira', advogado: 'Dr Ruan Pietro', digitosCpf: [0, 1], ehEscalao48h: false, departamento: 'Andamento Processual' },
  { id: 9, polo: 'PR_RR', colaboradorNome: 'Juliana Puhlmann', advogado: 'Dra Claudia Gonçalves', digitosCpf: [2, 3], ehEscalao48h: false, departamento: 'Andamento Processual' },
  { id: 10, polo: 'MA_ES_PE', colaboradorNome: 'Vanessa Barbosa', advogado: 'Lucas Gomes', digitosCpf: [4, 5], ehEscalao48h: false, departamento: 'Andamento Processual' },
];

export const MOCK_TAREFAS = [
  {
    id: 1001,
    titulo: 'Andamento Cobrança - Carlos Eduardo de Oliveira',
    clienteNome: 'Carlos Eduardo de Oliveira',
    cpfCliente: '142.893.201-00',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 0,
    poloCobranca: 'RJ',
    equipeCobrancaColaboradorNome: 'Nathalia Leão',
    equipeCobrancaAdvogado: 'Dra Graziela',
    situacaoPrazo: 'no_prazo',
    prazoFinal: '2026-09-20T18:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1001/',
    emEscalao48h: false,
  },
  {
    id: 1002,
    titulo: 'Execução de Título - Mariana Albuquerque Costa',
    clienteNome: 'Mariana Albuquerque Costa',
    cpfCliente: '298.415.760-11',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 1,
    poloCobranca: 'RJ',
    equipeCobrancaColaboradorNome: 'Francielle Furtado',
    equipeCobrancaAdvogado: 'Dr Lucas Puzanovsky',
    situacaoPrazo: 'atrasada',
    prazoFinal: '2026-08-25T15:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1002/',
    emEscalao48h: false,
  },
  {
    id: 1003,
    titulo: 'Acordo Homologado - Roberto Santoro Mendes',
    clienteNome: 'Roberto Santoro Mendes',
    cpfCliente: '371.902.548-22',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 2,
    poloCobranca: 'RJ',
    equipeCobrancaColaboradorNome: 'Marcio Freiman',
    equipeCobrancaAdvogado: 'Dr Bruno Pimentel',
    situacaoPrazo: 'concluida',
    prazoFinal: '2026-08-30T12:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1003/',
    emEscalao48h: false,
  },
  {
    id: 1004,
    titulo: 'Cobrança Extrajudicial - Fernando Bezerra Lima',
    clienteNome: 'Fernando Bezerra Lima',
    cpfCliente: '450.812.934-33',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 3,
    poloCobranca: 'SP',
    equipeCobrancaColaboradorNome: 'Kaio Luna',
    equipeCobrancaAdvogado: 'Dra Gabriela Torres',
    situacaoPrazo: 'atrasada',
    prazoFinal: '2026-08-20T17:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1004/',
    emEscalao48h: false,
  },
  {
    id: 1005,
    titulo: 'Revisão Contratual - Beatriz Fagundes Rocha',
    clienteNome: 'Beatriz Fagundes Rocha',
    cpfCliente: '519.340.671-44',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 4,
    poloCobranca: 'SP',
    equipeCobrancaColaboradorNome: 'Kaio Luna',
    equipeCobrancaAdvogado: 'Dra Gabriela Torres',
    situacaoPrazo: 'no_prazo',
    prazoFinal: '2026-09-18T16:30:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1005/',
    emEscalao48h: false,
  },
  {
    id: 1006,
    titulo: 'Cobrança Judicial - Rodrigo Martins Pires',
    clienteNome: 'Rodrigo Martins Pires',
    cpfCliente: '682.190.435-55',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 5,
    poloCobranca: 'BA',
    equipeCobrancaColaboradorNome: 'João Carmo',
    equipeCobrancaAdvogado: 'Dra Debora Correa',
    situacaoPrazo: 'no_prazo',
    prazoFinal: '2026-09-22T14:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1006/',
    emEscalao48h: false,
  },
  {
    id: 1007,
    titulo: 'Notificação Preliminar - Amanda Guimarães Siqueira',
    clienteNome: 'Amanda Guimarães Siqueira',
    cpfCliente: '791.203.846-66',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 6,
    poloCobranca: 'BA',
    equipeCobrancaColaboradorNome: 'João Carmo',
    equipeCobrancaAdvogado: 'Dra Debora Correa',
    situacaoPrazo: 'atrasada',
    prazoFinal: '2026-08-15T11:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1007/',
    emEscalao48h: false,
  },
  {
    id: 1008,
    titulo: 'Negociação Asaas - Patricia Ramos Peixoto',
    clienteNome: 'Patricia Ramos Peixoto',
    cpfCliente: '834.567.129-77',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 7,
    poloCobranca: 'MG_AM',
    equipeCobrancaColaboradorNome: 'Otavio Souza',
    equipeCobrancaAdvogado: 'Dr Diego Monteiro',
    situacaoPrazo: 'no_prazo',
    prazoFinal: '2026-09-25T10:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1008/',
    emEscalao48h: false,
  },
  {
    id: 1009,
    titulo: 'Quitado Integralmente - Lucas Andrade Nogueira',
    clienteNome: 'Lucas Andrade Nogueira',
    cpfCliente: '920.147.358-88',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 8,
    poloCobranca: 'DF_PA_MS',
    equipeCobrancaColaboradorNome: 'Camilla Suelen',
    equipeCobrancaAdvogado: 'Dra Jéssica',
    situacaoPrazo: 'concluida',
    prazoFinal: '2026-08-28T18:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1009/',
    emEscalao48h: false,
  },
  {
    id: 1010,
    titulo: 'Cobrança em Atraso - Vinicius Toledo Fontes',
    clienteNome: 'Vinicius Toledo Fontes',
    cpfCliente: '105.892.439-99',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 9,
    poloCobranca: 'DF_PA_MS',
    equipeCobrancaColaboradorNome: 'Camilla Suelen',
    equipeCobrancaAdvogado: 'Dra Jéssica',
    situacaoPrazo: 'atrasada',
    prazoFinal: '2026-08-10T09:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1010/',
    emEscalao48h: false,
  },
  {
    id: 1011,
    titulo: 'Execução Inicial - Danielle Souza Medeiros',
    clienteNome: 'Danielle Souza Medeiros',
    cpfCliente: '214.930.582-01',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 1,
    poloCobranca: 'GO_RS_MT',
    equipeCobrancaColaboradorNome: 'Raphaela Pereira',
    equipeCobrancaAdvogado: 'Dr Ruan Pietro',
    situacaoPrazo: 'no_prazo',
    prazoFinal: '2026-09-30T17:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1011/',
    emEscalao48h: false,
  },
  {
    id: 1012,
    titulo: 'Pendência Bancária - Gustavo Henrique Freitas',
    clienteNome: 'Gustavo Henrique Freitas',
    cpfCliente: '348.109.675-02',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 2,
    poloCobranca: 'PR_RR',
    equipeCobrancaColaboradorNome: 'Juliana Puhlmann',
    equipeCobrancaAdvogado: 'Dra Claudia Gonçalves',
    situacaoPrazo: 'atrasada',
    prazoFinal: '2026-08-01T15:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1012/',
    emEscalao48h: false,
  },
  {
    id: 1013,
    titulo: 'Finalização Termo - Camila Barros Paiva',
    clienteNome: 'Camila Barros Paiva',
    cpfCliente: '462.831.904-03',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 3,
    poloCobranca: 'MA_ES_PE',
    equipeCobrancaColaboradorNome: 'Vanessa Barbosa',
    equipeCobrancaAdvogado: 'Lucas Gomes',
    situacaoPrazo: 'concluida',
    prazoFinal: '2026-08-20T16:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1013/',
    emEscalao48h: false,
  },
  {
    id: 1014,
    titulo: 'Andamento Inicial - Thiago Carneiro Viana',
    clienteNome: 'Thiago Carneiro Viana',
    cpfCliente: '591.240.783-04',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 4,
    poloCobranca: 'RN_PB_CE',
    equipeCobrancaColaboradorNome: 'Vanessa Barbosa',
    equipeCobrancaAdvogado: 'Lucas Gomes',
    situacaoPrazo: 'no_prazo',
    prazoFinal: '2026-09-28T14:30:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1014/',
    emEscalao48h: false,
  },
  {
    id: 1015,
    titulo: 'Contingência 48h - Priscilla Duarte Carvalho',
    clienteNome: 'Priscilla Duarte Carvalho',
    cpfCliente: '673.819.042-05',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 5,
    poloCobranca: 'AC_AL_AP_PI_RO_SC_SE_TO',
    equipeCobrancaColaboradorNome: 'Kaio Luna',
    equipeCobrancaAdvogado: 'Dra Gabriela Torres',
    situacaoPrazo: 'atrasada',
    prazoFinal: '2026-08-12T11:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1015/',
    emEscalao48h: true,
  },
  {
    id: 1016,
    titulo: 'Cobrança Extraordinária - Leandro Vasconcelos',
    clienteNome: 'Leandro Vasconcelos',
    cpfCliente: '780.392.146-06',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 6,
    poloCobranca: 'RJ',
    equipeCobrancaColaboradorNome: 'Marcio Freiman',
    equipeCobrancaAdvogado: 'Dr Bruno Pimentel',
    situacaoPrazo: 'no_prazo',
    prazoFinal: '2026-09-19T18:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1016/',
    emEscalao48h: false,
  },
  {
    id: 1017,
    titulo: 'Acordo Assinado - Vanessa Muniz Teodoro',
    clienteNome: 'Vanessa Muniz Teodoro',
    cpfCliente: '891.450.237-07',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 7,
    poloCobranca: 'SP',
    equipeCobrancaColaboradorNome: 'Kaio Luna',
    equipeCobrancaAdvogado: 'Dra Gabriela Torres',
    situacaoPrazo: 'concluida',
    prazoFinal: '2026-08-29T10:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1017/',
    emEscalao48h: false,
  },
  {
    id: 1018,
    titulo: 'Cobrança Vencida - Marcelo Brandão Cavalcanti',
    clienteNome: 'Marcelo Brandão Cavalcanti',
    cpfCliente: '902.581.346-08',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 8,
    poloCobranca: 'MG_AM',
    equipeCobrancaColaboradorNome: 'Otavio Souza',
    equipeCobrancaAdvogado: 'Dr Diego Monteiro',
    situacaoPrazo: 'atrasada',
    prazoFinal: '2026-08-05T12:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1018/',
    emEscalao48h: false,
  },
  {
    id: 1019,
    titulo: 'Processo Em Andamento - Aline Cristina Faria',
    clienteNome: 'Aline Cristina Faria',
    cpfCliente: '134.908.625-09',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 9,
    poloCobranca: 'BA',
    equipeCobrancaColaboradorNome: 'João Carmo',
    equipeCobrancaAdvogado: 'Dra Debora Correa',
    situacaoPrazo: 'no_prazo',
    prazoFinal: '2026-09-24T16:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1019/',
    emEscalao48h: false,
  },
  {
    id: 1020,
    titulo: 'Termo Quitação - Felipe Antunes Miranda',
    clienteNome: 'Felipe Antunes Miranda',
    cpfCliente: '245.019.736-10',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 0,
    poloCobranca: 'RJ',
    equipeCobrancaColaboradorNome: 'Nathalia Leão',
    equipeCobrancaAdvogado: 'Dra Graziela',
    situacaoPrazo: 'concluida',
    prazoFinal: '2026-08-31T17:30:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1020/',
    emEscalao48h: false,
  },
];

export const ADMINS_PERMISSOES = [
  'Caio Marques',
  'Lorena Pontes',
  'Vagner Rodrigues',
  'Handerson Salles',
  'Handerson Sales',
];

export const MOCK_COLABORADORES_ANDAMENTO = [
  { id: 201, nome: 'Nathalia Leão', departamento: 'Andamento Processual', polo: 'RJ', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 202, nome: 'Francielle Furtado', departamento: 'Andamento Processual', polo: 'RJ', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 203, nome: 'Marcio Freiman', departamento: 'Andamento Processual', polo: 'RJ', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 204, nome: 'Camilla Suelen Duarte', departamento: 'Andamento Processual', polo: 'DF_PA_MS', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 205, nome: 'João Carmo', departamento: 'Andamento Processual', polo: 'BA', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 206, nome: 'Vanessa Barbosa', departamento: 'Andamento Processual', polo: 'MA_ES_PE', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 207, nome: 'Kaio Luna', departamento: 'Andamento Processual', polo: 'SP', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 208, nome: 'Otavio Souza', departamento: 'Andamento Processual', polo: 'MG_AM', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 209, nome: 'Raphaela Pereira Vaz', departamento: 'Andamento Processual', polo: 'GO_RS_MT', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 210, nome: 'Juliana Puhlmann', departamento: 'Andamento Processual', polo: 'PR_RR', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 211, nome: 'Amanda Guimarães', departamento: 'Andamento Processual', polo: 'BA', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 212, nome: 'Rodrigo Martins Pires', departamento: 'Andamento Processual', polo: 'BA', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 213, nome: 'Patricia Ramos Peixoto', departamento: 'Andamento Processual', polo: 'MG_AM', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 214, nome: 'Lucas Andrade Nogueira', departamento: 'Andamento Processual', polo: 'DF_PA_MS', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 215, nome: 'Danielle Souza Medeiros', departamento: 'Andamento Processual', polo: 'GO_RS_MT', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 216, nome: 'Priscilla Duarte Carvalho', departamento: 'Andamento Processual', polo: 'AC_AL_AP_PI_RO_SC_SE_TO', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 217, nome: 'Leandro Vasconcelos', departamento: 'Andamento Processual', polo: 'RJ', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 218, nome: 'Vanessa Muniz Teodoro', departamento: 'Andamento Processual', polo: 'SP', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
];

