export const MOCK_POLOS = [
  { codigo: 'RJ', rotulo: 'RJ - Rio de Janeiro', ufs: ['RJ'] },
  { codigo: 'SP', rotulo: 'SP - São Paulo', ufs: ['SP'] },
  { codigo: 'DF_PA_MS', rotulo: 'DF - PA - MS', ufs: ['DF', 'PA', 'MS'] },
  { codigo: 'MG_AM', rotulo: 'MG - AM', ufs: ['MG', 'AM'] },
  { codigo: 'BA', rotulo: 'BA - Bahia', ufs: ['BA'] },
  { codigo: 'GO_RS_MT', rotulo: 'GO - RS - MT', ufs: ['GO', 'RS', 'MT'] },
  { codigo: 'PR_RR', rotulo: 'PR - RR', ufs: ['PR', 'RR'] },
  { codigo: 'AC_AL_AP_PI_RO_SC_SE_TO', rotulo: 'AC - AL - AP - PI - RO - SC - SE - TO', ufs: ['AC', 'AL', 'AP', 'PI', 'RO', 'SC', 'SE', 'TO'] },
  { codigo: 'MA_ES_PE', rotulo: 'MA - ES - PE', ufs: ['MA', 'ES', 'PE'] },
  { codigo: 'RN_PB_CE', rotulo: 'RN - PB - CE', ufs: ['RN', 'PB', 'CE'] },
];

/**
 * Cadastro OFICIAL de Cobradores, Faixas de CPF e Advogados (Anexo 2).
 * 49 regras oficiais distribuídas entre os 10 polos regionais.
 */
export const MOCK_REGRAS = [
  // 1. RJ — Rio de Janeiro
  { id: 1, polo: 'RJ', colaboradorNome: 'Nathalia Leão', advogado: 'Dra Graziela', digitosCpf: [0], ehEscalao48h: false, email: 'nathalia.leao@dapadvocacia.com.br', departamento: 'Andamento Processual' },
  { id: 2, polo: 'RJ', colaboradorNome: 'Francielle Furtado', advogado: 'Dr Lucas Puzanovsky', digitosCpf: [1], ehEscalao48h: false, email: 'francielle.furtado@dapadvocacia.com.br', departamento: 'Andamento Processual' },
  { id: 3, polo: 'RJ', colaboradorNome: 'Marcio Freiman', advogado: 'Dr Bruno Pimentel', digitosCpf: [2], ehEscalao48h: false, email: 'marcio.freiman@dapadvocacia.com.br', departamento: 'Andamento Processual' },
  { id: 4, polo: 'RJ', colaboradorNome: 'Camilla Suelen Duarte de Souza', advogado: 'Dra Jéssica', digitosCpf: [3], ehEscalao48h: false, email: 'camilla.souza@dapadvocacia.com.br', departamento: 'Andamento Processual' },
  { id: 5, polo: 'RJ', colaboradorNome: 'João Carmo', advogado: 'Dra Debora Correa', digitosCpf: [4], ehEscalao48h: false, email: 'joao.carmo@dapadvocacia.com.br', departamento: 'Andamento Processual' },
  { id: 6, polo: 'RJ', colaboradorNome: 'Vanessa Barbosa', advogado: 'Lucas Gomes', digitosCpf: [5], ehEscalao48h: false, email: null, departamento: 'Andamento Processual' },
  { id: 7, polo: 'RJ', colaboradorNome: 'Kaio Luna', advogado: 'Dra Gabriela Torres', digitosCpf: [6], ehEscalao48h: false, email: 'kaio.luna@dapadvocacia.com.br', departamento: 'Andamento Processual' },
  { id: 8, polo: 'RJ', colaboradorNome: 'Otavio Souza', advogado: 'Dr Diego Monteiro', digitosCpf: [7], ehEscalao48h: false, email: 'otavio.souza@dapadvocacia.com.br', departamento: 'Andamento Processual' },
  { id: 9, polo: 'RJ', colaboradorNome: 'Raphaela Pereira Vaz', advogado: 'Dr Ruan Pietro', digitosCpf: [8], ehEscalao48h: false, email: 'raphaela.pereira@dapadvocacia.com.br', departamento: 'Andamento Processual' },
  { id: 10, polo: 'RJ', colaboradorNome: 'Juliana Puhlmann Boisson Barboza', advogado: 'Dra Claudia Gonçalves', digitosCpf: [9], ehEscalao48h: false, email: 'juliana.puhlmann@dapadvocacia.com.br', departamento: 'Andamento Processual' },
  { id: 11, polo: 'RJ', colaboradorNome: 'Ana Catarina', advogado: 'Dr Wanderson Silva', digitosCpf: [], ehEscalao48h: true, email: 'ana.ribeiro@dapadvocacia.com.br', departamento: 'Andamento Processual' },

  // 2. DF — PA — MS
  { id: 12, polo: 'DF_PA_MS', colaboradorNome: 'Leila', advogado: 'Dr. Matheus Jardin', digitosCpf: [0, 1, 2], ehEscalao48h: false, email: 'leila.lopes@dapadvocacia.com.br', departamento: 'Andamento Processual' },
  { id: 13, polo: 'DF_PA_MS', colaboradorNome: 'Luciana', advogado: 'Dra. Isabelly Antunes', digitosCpf: [3, 4, 5], ehEscalao48h: false, email: 'luciana.pereira@dapadvocacia.com.br', departamento: 'Andamento Processual' },
  { id: 14, polo: 'DF_PA_MS', colaboradorNome: 'Wanessa', advogado: 'Dr. Fabio Moreira', digitosCpf: [6, 7, 8, 9], ehEscalao48h: false, email: 'wanessa.financeiro@dapadvocacia.com.br', departamento: 'Andamento Processual' },

  // 3. MG e AM
  { id: 15, polo: 'MG_AM', colaboradorNome: 'Lays Lima (Gerente de cobrança)', advogado: 'Dr. Vitor Pereira', digitosCpf: [0, 1, 2, 3], ehEscalao48h: false, email: 'lays.lima@dapadvocacia.com.br', departamento: 'Andamento Processual' },
  { id: 16, polo: 'MG_AM', colaboradorNome: 'Thays Evres', advogado: 'Dra Rose Brandão', digitosCpf: [4, 5, 6], ehEscalao48h: false, email: 'thays.evres@dapadvocacia.com.br', departamento: 'Andamento Processual' },
  { id: 17, polo: 'MG_AM', colaboradorNome: 'Renato Silva', advogado: 'Dra Izabela Ribeiro', digitosCpf: [7, 8, 9], ehEscalao48h: false, email: 'renato.silva@dapadvocacia.com.br', departamento: 'Andamento Processual' },
  { id: 18, polo: 'MG_AM', colaboradorNome: 'Gabriela Vieira', advogado: null, digitosCpf: [], ehEscalao48h: true, email: null, departamento: 'Andamento Processual' },
  { id: 19, polo: 'MG_AM', colaboradorNome: 'Marcelo Silva', advogado: null, digitosCpf: [], ehEscalao48h: true, email: null, departamento: 'Andamento Processual' },

  // 4. SP
  { id: 20, polo: 'SP', colaboradorNome: 'Matheus', advogado: 'Dr. Gabriel Buentes', digitosCpf: [0, 1, 2, 3], ehEscalao48h: false, email: 'matheus.almeida@dapadvocacia.com.br', departamento: 'Andamento Processual' },
  { id: 21, polo: 'SP', colaboradorNome: 'Jackson George', advogado: 'Dr. Gabriela Nunes', digitosCpf: [4, 5, 6], ehEscalao48h: false, email: 'jackson.george@dapadvocacia.com.br', departamento: 'Andamento Processual' },
  { id: 22, polo: 'SP', colaboradorNome: 'Jose Cupertino', advogado: 'Dr. Gabryella Soares', digitosCpf: [7, 8, 9], ehEscalao48h: false, email: 'jose.cupertino@dapadvocacia.com.br', departamento: 'Andamento Processual' },
  { id: 23, polo: 'SP', colaboradorNome: 'Sophia Sodre', advogado: 'Dr. Juliana Silva', digitosCpf: [], ehEscalao48h: true, email: 'sophia.dias@dapadvocacia.com.br', departamento: 'Andamento Processual' },
  { id: 24, polo: 'SP', colaboradorNome: 'Geovanna Silva', advogado: 'Dr. Romulo Sally', digitosCpf: [], ehEscalao48h: true, email: 'geovanna.silva@dapadvocacia.com.br', departamento: 'Andamento Processual' },

  // 5. Bahia
  { id: 25, polo: 'BA', colaboradorNome: 'Hugo Guedes', advogado: 'Dr. Jonathan Weber', digitosCpf: [0, 1], ehEscalao48h: false, email: 'hugo.guedes@dapadvocacia.com.br', departamento: 'Andamento Processual' },
  { id: 26, polo: 'BA', colaboradorNome: 'Luan Machado', advogado: 'Dra. Marina', digitosCpf: [2, 3], ehEscalao48h: false, email: 'luan.machado@blindagemfinanceira.com.br', departamento: 'Andamento Processual' },
  { id: 27, polo: 'BA', colaboradorNome: 'Isabelly Nascimento', advogado: 'Dra. Jessica', digitosCpf: [4, 5], ehEscalao48h: false, email: 'isabelly.nascimento@dapadvocacia.com.br', departamento: 'Andamento Processual' },
  { id: 28, polo: 'BA', colaboradorNome: 'Camila Lima', advogado: 'Dr. Anderson Gregorio', digitosCpf: [6, 7], ehEscalao48h: false, email: 'camila.lima@dapadvocacia.com.br', departamento: 'Andamento Processual' },
  { id: 29, polo: 'BA', colaboradorNome: 'Diogo Pereira', advogado: 'Dra. Stephani Silva', digitosCpf: [8, 9], ehEscalao48h: false, email: 'diogo.pereira@dapadvocacia.com.br', departamento: 'Andamento Processual' },
  { id: 30, polo: 'BA', colaboradorNome: 'Lidiene Santos', advogado: 'Dra. Jamile Andrade', digitosCpf: [], ehEscalao48h: true, email: 'lidiene.santos@dapadvocacia.com.br', departamento: 'Andamento Processual' },
  { id: 31, polo: 'BA', colaboradorNome: 'Luiz Felipe', advogado: null, digitosCpf: [], ehEscalao48h: true, email: 'luiz.felipe@dapadvocacia.com.br', departamento: 'Andamento Processual' },

  // 6. GO — RS — MT
  { id: 32, polo: 'GO_RS_MT', colaboradorNome: 'Thayná Fortunato (Gerente)', advogado: 'Dra. Monalisa Ferreira', digitosCpf: [0, 1], ehEscalao48h: false, email: null, departamento: 'Andamento Processual' },
  { id: 33, polo: 'GO_RS_MT', colaboradorNome: 'Andrews Santos', advogado: 'Dr. Paula Gomes', digitosCpf: [2, 5], ehEscalao48h: false, email: null, departamento: 'Andamento Processual' },
  { id: 34, polo: 'GO_RS_MT', colaboradorNome: 'Leticia Castro', advogado: 'Anna Ferreira', digitosCpf: [3, 4], ehEscalao48h: false, email: null, departamento: 'Andamento Processual' },
  { id: 35, polo: 'GO_RS_MT', colaboradorNome: 'Gabrielle Vale', advogado: 'Dra. Ana Carolina Lopes', digitosCpf: [6, 7], ehEscalao48h: false, email: null, departamento: 'Andamento Processual' },
  { id: 36, polo: 'GO_RS_MT', colaboradorNome: 'Gabriel Lima', advogado: 'Pablo Nacif', digitosCpf: [8, 9], ehEscalao48h: false, email: null, departamento: 'Andamento Processual' },
  { id: 37, polo: 'GO_RS_MT', colaboradorNome: 'Natanael Brito', advogado: 'Dr. Ricardo Soares', digitosCpf: [], ehEscalao48h: true, email: null, departamento: 'Andamento Processual' },
  { id: 38, polo: 'GO_RS_MT', colaboradorNome: 'Rafael Telles', advogado: null, digitosCpf: [], ehEscalao48h: true, email: null, departamento: 'Andamento Processual' },

  // 7. Estado: PR / RR
  { id: 39, polo: 'PR_RR', colaboradorNome: 'Jonathan Yuri', advogado: null, digitosCpf: [0, 1], ehEscalao48h: false, email: null, departamento: 'Andamento Processual' },
  { id: 40, polo: 'PR_RR', colaboradorNome: 'Ricardo Marinho', advogado: 'Dr Elizabeth Nogueira', digitosCpf: [2, 3], ehEscalao48h: false, email: 'ricardo.marinho@dapadvocacia.com.br', departamento: 'Andamento Processual' },
  { id: 41, polo: 'PR_RR', colaboradorNome: 'Karolina Souza', advogado: null, digitosCpf: [4, 5], ehEscalao48h: false, email: null, departamento: 'Andamento Processual' },
  { id: 42, polo: 'PR_RR', colaboradorNome: "Lorrane Sant'Anna", advogado: null, digitosCpf: [6, 7], ehEscalao48h: false, email: null, departamento: 'Andamento Processual' },
  { id: 43, polo: 'PR_RR', colaboradorNome: 'Cassia (nova)', advogado: null, digitosCpf: [8, 9], ehEscalao48h: false, email: null, departamento: 'Andamento Processual' },

  // 8. AC, AL, AP, PI, RO, SC, SE, TO
  { id: 44, polo: 'AC_AL_AP_PI_RO_SC_SE_TO', colaboradorNome: 'Liliane Pandolpho', advogado: 'Dr. Ricardo Neves', digitosCpf: [0, 1, 2, 3, 4], ehEscalao48h: false, email: 'liliane.pandolpho@dapadvocacia.com.br', departamento: 'Andamento Processual' },
  { id: 45, polo: 'AC_AL_AP_PI_RO_SC_SE_TO', colaboradorNome: 'Victor Pinheiro', advogado: null, digitosCpf: [5, 6, 7, 8, 9], ehEscalao48h: false, email: 'victor.pinheiro@dapadvocacia.com.br', departamento: 'Andamento Processual' },

  // 9. MA / ES / PE
  { id: 46, polo: 'MA_ES_PE', colaboradorNome: 'Taina Soueiro', advogado: null, digitosCpf: [0, 1, 2, 3, 4], ehEscalao48h: false, email: null, departamento: 'Andamento Processual' },
  { id: 47, polo: 'MA_ES_PE', colaboradorNome: 'Cristiane Caetano', advogado: null, digitosCpf: [5, 6, 7, 8, 9], ehEscalao48h: false, email: null, departamento: 'Andamento Processual' },

  // 10. RN / PB / CE
  { id: 48, polo: 'RN_PB_CE', colaboradorNome: 'Patrick Méro', advogado: null, digitosCpf: [0, 1, 2, 3, 4], ehEscalao48h: false, email: 'patrick.gonzaga@dapadvocacia.com.br', departamento: 'Andamento Processual' },
  { id: 49, polo: 'RN_PB_CE', colaboradorNome: 'Renan Chaves', advogado: null, digitosCpf: [5, 6, 7, 8, 9], ehEscalao48h: false, email: 'renan.chaves@dapadvocacia.com.br', departamento: 'Andamento Processual' },
];

/**
 * Helper para resolver Cobrador e Advogado de qualquer tarefa com base nas regras do Anexo 2.
 */
export function resolverCobradorEAdvogado(polo, digitoCpf, eh48h = false) {
  const regra = MOCK_REGRAS.find((r) => {
    if (r.polo !== polo) return false;
    if (eh48h) return !!r.ehEscalao48h;
    if (digitoCpf != null && Array.isArray(r.digitosCpf)) {
      return r.digitosCpf.includes(digitoCpf);
    }
    return false;
  });

  return {
    cobrador: regra?.colaboradorNome || '—',
    advogado: regra?.advogado || 'Sem advogado',
  };
}

/**
 * 20 tarefas realistas mapeadas 100% de acordo com Anexo 2.
 */
export const MOCK_TAREFAS = [
  {
    id: 1001,
    titulo: 'Andamento Cobrança - Carlos Eduardo de Oliveira',
    clienteNome: 'Carlos Eduardo de Oliveira',
    cpfCliente: '142.893.201-00',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 0,
    poloCobranca: 'RJ',
    equipeCobrancaColaboradorNome: 'Nathalia Leão',
    equipeCobrancaAdvogado: 'Dra Graziela',
    situacaoPrazo: 'no_prazo',
    prazoFinal: '2026-09-20T18:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1001/',
    emEscalao48h: false,
  },
  {
    id: 1002,
    titulo: 'Execução de Título - Mariana Albuquerque Costa',
    clienteNome: 'Mariana Albuquerque Costa',
    cpfCliente: '298.415.760-11',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 1,
    poloCobranca: 'RJ',
    equipeCobrancaColaboradorNome: 'Francielle Furtado',
    equipeCobrancaAdvogado: 'Dr Lucas Puzanovsky',
    situacaoPrazo: 'atrasada',
    prazoFinal: '2026-08-25T15:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1002/',
    emEscalao48h: false,
  },
  {
    id: 1003,
    titulo: 'Acordo Homologado - Roberto Santoro Mendes',
    clienteNome: 'Roberto Santoro Mendes',
    cpfCliente: '371.902.548-22',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 2,
    poloCobranca: 'RJ',
    equipeCobrancaColaboradorNome: 'Marcio Freiman',
    equipeCobrancaAdvogado: 'Dr Bruno Pimentel',
    situacaoPrazo: 'concluida',
    prazoFinal: '2026-08-30T12:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1003/',
    emEscalao48h: false,
  },
  {
    id: 1004,
    titulo: 'Cobrança Extrajudicial - Fernando Bezerra Lima',
    clienteNome: 'Fernando Bezerra Lima',
    cpfCliente: '450.812.934-03',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 3,
    poloCobranca: 'SP',
    equipeCobrancaColaboradorNome: 'Matheus',
    equipeCobrancaAdvogado: 'Dr. Gabriel Buentes',
    situacaoPrazo: 'atrasada',
    prazoFinal: '2026-08-20T17:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1004/',
    emEscalao48h: false,
  },
  {
    id: 1005,
    titulo: 'Revisão Contratual - Beatriz Fagundes Rocha',
    clienteNome: 'Beatriz Fagundes Rocha',
    cpfCliente: '519.340.671-44',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 4,
    poloCobranca: 'SP',
    equipeCobrancaColaboradorNome: 'Jackson George',
    equipeCobrancaAdvogado: 'Dr. Gabriela Nunes',
    situacaoPrazo: 'no_prazo',
    prazoFinal: '2026-09-18T16:30:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1005/',
    emEscalao48h: false,
  },
  {
    id: 1006,
    titulo: 'Cobrança Judicial - Rodrigo Martins Pires',
    clienteNome: 'Rodrigo Martins Pires',
    cpfCliente: '682.190.435-01',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 1,
    poloCobranca: 'BA',
    equipeCobrancaColaboradorNome: 'Hugo Guedes',
    equipeCobrancaAdvogado: 'Dr. Jonathan Weber',
    situacaoPrazo: 'no_prazo',
    prazoFinal: '2026-09-22T14:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1006/',
    emEscalao48h: false,
  },
  {
    id: 1007,
    titulo: 'Notificação Preliminar - Amanda Guimarães Siqueira',
    clienteNome: 'Amanda Guimarães Siqueira',
    cpfCliente: '734.509.812-33',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 3,
    poloCobranca: 'BA',
    equipeCobrancaColaboradorNome: 'Luan Machado',
    equipeCobrancaAdvogado: 'Dra. Marina',
    situacaoPrazo: 'no_prazo',
    prazoFinal: '2026-09-25T11:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1007/',
    emEscalao48h: false,
  },
  {
    id: 1008,
    titulo: 'Execução de Sentença - Patrícia Ramos Peixoto',
    clienteNome: 'Patrícia Ramos Peixoto',
    cpfCliente: '891.243.670-22',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 2,
    poloCobranca: 'MG_AM',
    equipeCobrancaColaboradorNome: 'Lays Lima (Gerente de cobrança)',
    equipeCobrancaAdvogado: 'Dr. Vitor Pereira',
    situacaoPrazo: 'atrasada',
    prazoFinal: '2026-08-28T18:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1008/',
    emEscalao48h: false,
  },
  {
    id: 1009,
    titulo: 'Acompanhamento Recursal - Lucas Andrade Nogueira',
    clienteNome: 'Lucas Andrade Nogueira',
    cpfCliente: '912.876.543-01',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 1,
    poloCobranca: 'DF_PA_MS',
    equipeCobrancaColaboradorNome: 'Leila',
    equipeCobrancaAdvogado: 'Dr. Matheus Jardin',
    situacaoPrazo: 'no_prazo',
    prazoFinal: '2026-09-19T17:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1009/',
    emEscalao48h: false,
  },
  {
    id: 1010,
    titulo: 'Proposta de Parcelamento - Vinícius Toledo Fontes',
    clienteNome: 'Vinícius Toledo Fontes',
    cpfCliente: '023.456.789-44',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 4,
    poloCobranca: 'DF_PA_MS',
    equipeCobrancaColaboradorNome: 'Luciana',
    equipeCobrancaAdvogado: 'Dra. Isabelly Antunes',
    situacaoPrazo: 'concluida',
    prazoFinal: '2026-08-29T10:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1010/',
    emEscalao48h: false,
  },
  {
    id: 1011,
    titulo: 'Negociação Direta - Danielle Souza Medeiros',
    clienteNome: 'Danielle Souza Medeiros',
    cpfCliente: '156.789.234-00',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 0,
    poloCobranca: 'GO_RS_MT',
    equipeCobrancaColaboradorNome: 'Thayná Fortunato (Gerente)',
    equipeCobrancaAdvogado: 'Dra. Monalisa Ferreira',
    situacaoPrazo: 'no_prazo',
    prazoFinal: '2026-09-21T15:30:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1011/',
    emEscalao48h: false,
  },
  {
    id: 1012,
    titulo: 'Impugnação de Cálculos - Gustavo Henrique Freitas',
    clienteNome: 'Gustavo Henrique Freitas',
    cpfCliente: '267.890.345-33',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 3,
    poloCobranca: 'GO_RS_MT',
    equipeCobrancaColaboradorNome: 'Leticia Castro',
    equipeCobrancaAdvogado: 'Anna Ferreira',
    situacaoPrazo: 'atrasada',
    prazoFinal: '2026-08-22T12:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1012/',
    emEscalao48h: false,
  },
  {
    id: 1013,
    titulo: 'Busca e Apreensão - Camila Barros Paiva',
    clienteNome: 'Camila Barros Paiva',
    cpfCliente: '378.901.456-22',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 2,
    poloCobranca: 'PR_RR',
    equipeCobrancaColaboradorNome: 'Ricardo Marinho',
    equipeCobrancaAdvogado: 'Dr Elizabeth Nogueira',
    situacaoPrazo: 'no_prazo',
    prazoFinal: '2026-09-24T18:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1013/',
    emEscalao48h: false,
  },
  {
    id: 1014,
    titulo: 'Quitação Parcial - Thiago Carneiro Viana',
    clienteNome: 'Thiago Carneiro Viana',
    cpfCliente: '489.012.567-33',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 3,
    poloCobranca: 'AC_AL_AP_PI_RO_SC_SE_TO',
    equipeCobrancaColaboradorNome: 'Liliane Pandolpho',
    equipeCobrancaAdvogado: 'Dr. Ricardo Neves',
    situacaoPrazo: 'atrasada',
    prazoFinal: '2026-08-24T14:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1014/',
    emEscalao48h: false,
  },
  {
    id: 1015,
    titulo: 'Liquidação de Sentença - Priscilla Duarte Carvalho',
    clienteNome: 'Priscilla Duarte Carvalho',
    cpfCliente: '590.123.678-77',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 7,
    poloCobranca: 'AC_AL_AP_PI_RO_SC_SE_TO',
    equipeCobrancaColaboradorNome: 'Victor Pinheiro',
    equipeCobrancaAdvogado: 'Sem advogado',
    situacaoPrazo: 'no_prazo',
    prazoFinal: '2026-09-26T17:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1015/',
    emEscalao48h: false,
  },
  {
    id: 1016,
    titulo: 'Renegociação de Dívida - Leandro Vasconcelos',
    clienteNome: 'Leandro Vasconcelos',
    cpfCliente: '601.234.789-22',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 2,
    poloCobranca: 'MA_ES_PE',
    equipeCobrancaColaboradorNome: 'Taina Soueiro',
    equipeCobrancaAdvogado: 'Sem advogado',
    situacaoPrazo: 'no_prazo',
    prazoFinal: '2026-09-23T16:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1016/',
    emEscalao48h: false,
  },
  {
    id: 1017,
    titulo: 'Penhora Online - Vanessa Muniz Teodoro',
    clienteNome: 'Vanessa Muniz Teodoro',
    cpfCliente: '712.345.890-11',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 1,
    poloCobranca: 'RN_PB_CE',
    equipeCobrancaColaboradorNome: 'Patrick Méro',
    equipeCobrancaAdvogado: 'Sem advogado',
    situacaoPrazo: 'atrasada',
    prazoFinal: '2026-08-26T18:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1017/',
    emEscalao48h: false,
  },
  {
    id: 1018,
    titulo: 'Despacho com Juiz - Marcelo Brandão Cavalcanti',
    clienteNome: 'Marcelo Brandão Cavalcanti',
    cpfCliente: '823.456.901-77',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 7,
    poloCobranca: 'SP',
    equipeCobrancaColaboradorNome: 'Jose Cupertino',
    equipeCobrancaAdvogado: 'Dr. Gabryella Soares',
    situacaoPrazo: 'no_prazo',
    prazoFinal: '2026-09-27T15:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1018/',
    emEscalao48h: false,
  },
  {
    id: 1019,
    titulo: 'Processo Em Andamento - Aline Cristina Faria',
    clienteNome: 'Aline Cristina Faria',
    cpfCliente: '134.908.625-55',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 5,
    poloCobranca: 'BA',
    equipeCobrancaColaboradorNome: 'Isabelly Nascimento',
    equipeCobrancaAdvogado: 'Dra. Jessica',
    situacaoPrazo: 'no_prazo',
    prazoFinal: '2026-09-24T16:00:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1019/',
    emEscalao48h: false,
  },
  {
    id: 1020,
    titulo: 'Termo Quitação - Felipe Antunes Miranda',
    clienteNome: 'Felipe Antunes Miranda',
    cpfCliente: '245.019.736-00',
    tipoDocumentoCliente: 'cpf',
    digitoCpfCliente: 0,
    poloCobranca: 'RJ',
    equipeCobrancaColaboradorNome: 'Nathalia Leão',
    equipeCobrancaAdvogado: 'Dra Graziela',
    situacaoPrazo: 'concluida',
    prazoFinal: '2026-08-31T17:30:00.000Z',
    linkTarefa: 'https://b24.bitrix24.com.br/workgroups/group/86/tasks/task/view/1020/',
    emEscalao48h: false,
  },
];

export const ADMINS_PERMISSOES = [
  'Caio Marques',
  'Lorena Pontes',
  'Vagner Rodrigues',
  'Handerson Sales',
  'Handerson Salles',
];

export const MOCK_COLABORADORES_ANDAMENTO = [
  { id: 201, nome: 'Nathalia Leão', departamento: 'Andamento Processual', polo: 'RJ', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 202, nome: 'Francielle Furtado', departamento: 'Andamento Processual', polo: 'RJ', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 203, nome: 'Marcio Freiman', departamento: 'Andamento Processual', polo: 'RJ', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 204, nome: 'Camilla Suelen Duarte de Souza', departamento: 'Andamento Processual', polo: 'RJ', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 205, nome: 'João Carmo', departamento: 'Andamento Processual', polo: 'RJ', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 206, nome: 'Vanessa Barbosa', departamento: 'Andamento Processual', polo: 'RJ', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 207, nome: 'Kaio Luna', departamento: 'Andamento Processual', polo: 'RJ', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 208, nome: 'Otavio Souza', departamento: 'Andamento Processual', polo: 'RJ', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 209, nome: 'Raphaela Pereira Vaz', departamento: 'Andamento Processual', polo: 'RJ', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 210, nome: 'Juliana Puhlmann Boisson Barboza', departamento: 'Andamento Processual', polo: 'RJ', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 211, nome: 'Leila', departamento: 'Andamento Processual', polo: 'DF_PA_MS', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 212, nome: 'Luciana', departamento: 'Andamento Processual', polo: 'DF_PA_MS', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 213, nome: 'Wanessa', departamento: 'Andamento Processual', polo: 'DF_PA_MS', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 214, nome: 'Lays Lima (Gerente de cobrança)', departamento: 'Andamento Processual', polo: 'MG_AM', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 215, nome: 'Thays Evres', departamento: 'Andamento Processual', polo: 'MG_AM', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 216, nome: 'Renato Silva', departamento: 'Andamento Processual', polo: 'MG_AM', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 217, nome: 'Matheus', departamento: 'Andamento Processual', polo: 'SP', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 218, nome: 'Jackson George', departamento: 'Andamento Processual', polo: 'SP', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 219, nome: 'Jose Cupertino', departamento: 'Andamento Processual', polo: 'SP', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 220, nome: 'Hugo Guedes', departamento: 'Andamento Processual', polo: 'BA', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 221, nome: 'Luan Machado', departamento: 'Andamento Processual', polo: 'BA', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 222, nome: 'Isabelly Nascimento', departamento: 'Andamento Processual', polo: 'BA', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 223, nome: 'Camila Lima', departamento: 'Andamento Processual', polo: 'BA', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 224, nome: 'Diogo Pereira', departamento: 'Andamento Processual', polo: 'BA', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 225, nome: 'Thayná Fortunato (Gerente)', departamento: 'Andamento Processual', polo: 'GO_RS_MT', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 226, nome: 'Andrews Santos', departamento: 'Andamento Processual', polo: 'GO_RS_MT', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 227, nome: 'Leticia Castro', departamento: 'Andamento Processual', polo: 'GO_RS_MT', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 228, nome: 'Ricardo Marinho', departamento: 'Andamento Processual', polo: 'PR_RR', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
  { id: 229, nome: 'Liliane Pandolpho', departamento: 'Andamento Processual', polo: 'AC_AL_AP_PI_RO_SC_SE_TO', permissoes: { painel: true, colaboradores: false, tarefas: true, permissoes: false } },
];
